//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelBookingSystemEntities : DbContext
    {
        public HotelBookingSystemEntities()
            : base("name=HotelBookingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<archiveCheckIn> archiveCheckIn { get; set; }
        public virtual DbSet<checkIn> checkIn { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<lodger> lodger { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<roomType> roomType { get; set; }
        public virtual DbSet<UsersAc> UsersAc { get; set; }
    }
}
