//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int id { get; set; }
        public string roomNo { get; set; }
        public int room_type_id { get; set; }
        public double price_per_day { get; set; }
        public int hotel_id { get; set; }
        public Nullable<bool> booked { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual hotel hotel1 { get; set; }
        public virtual roomType roomType { get; set; }
        public virtual roomType roomType1 { get; set; }
    }
}
